project_id = "kkeojjtopbpfbcmxlumx"

[functions.fetch-movie-data]
verify_jwt = true

[functions.import-tmdb-movies]
verify_jwt = true

[functions.cancel-sync]
verify_jwt = true

[functions.enrich-with-omdb]
verify_jwt = true

[functions.store-posters]
verify_jwt = true

[functions.refresh-movies-pipeline]
verify_jwt = true

[functions.import-new-movies-pipeline]
verify_jwt = true

[functions.log-activity]
verify_jwt = true

[functions.sync-single-movie]
verify_jwt = true

[functions.delete-movie]
verify_jwt = true