project_id = "kkeojjtopbpfbcmxlumx"

[functions.fetch-movie-data]
verify_jwt = true

[functions.import-tmdb-movies]
verify_jwt = true

[functions.cancel-sync]
verify_jwt = true

[functions.enrich-with-omdb]
verify_jwt = true